### ISSUE TITLE
Could not register the CGFont

### ISSUE THREAD

**Issue by BeamerCola** [LiveUI/Awesome#22]
I'm getting this error, but only with Brands.  `only:  [.regular]` works fine.  I've dropped and linked all the files to targets.  I'm using latest font files from fontawesome (webfont ttfs).

have you seen this before?

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The operation couldn’t be completed. (com.apple.CoreText.CTFontManagerErrorDomain error 105 - Could not register the CGFont '<CGFont (0x600002b71500): FontAwesome5BrandsRegular>')'
```

**Comment by BeamerCola** [comment]
@rafiki270 Oh cool.  Ok I dropped OTF files and they worked.  Good to know.  Something not working with Brands TTF.

**Comment by syky27** [comment]
For future reference I was getting this error, because I was using icon from the Pro pack inside statically initialized variable, which evaluates before `.didFinishLaunching...`

This was hard to find especially when you have wrapper around `AwesomeEnum` such as `Image.userFriendlyIconName()`. So you forget when you are are using `AwesomePro`

And you are the pig and the diff was larger than should be...

Cost me good 15 minutes to find it... So this might help someone...
